<?php

// Composer: "fzaninotto/faker": "v1.3.0"
use Faker\Factory as Faker;

class BrandTableSeeder extends Seeder {

	public function run()
	{
		date_default_timezone_set('America/Lima');
		$fecha = date('Y-m-d H:i:s');
		DB::statement("
			INSERT INTO `brands` (`name`,`created_at`) values
('ACURA', '$fecha'),
('ALFA ROMEO', '$fecha'),
('AMC', '$fecha'),
('ARO', '$fecha'),
('ASIA', '$fecha'),
('AUDI', '$fecha'),
('BAIC YINXIANG', '$fecha'),
('BAW', '$fecha'),
('BMW', '$fecha'),
('BRILLIANCE', '$fecha'),
('BUICK', '$fecha'),
('BYD', '$fecha'),
('Cadillac', '$fecha'),
('CAMC', '$fecha'),
('CHANGAN', '$fecha'),
('CHANGHE', '$fecha'),
('CHENGLONG', '$fecha'),
('CHERY', '$fecha'),
('CHEVROLET', '$fecha'),
('CHRYSLER', '$fecha'),
('CHUNZHOU', '$fecha'),
('CITROEN', '$fecha'),
('DAEWOO', '$fecha'),
('DAIHATSU', '$fecha'),
('DATSUN', '$fecha'),
('DIM', '$fecha'),
('DODGE', '$fecha'),
('DONGFENG', '$fecha'),
('EAGLE', '$fecha'),
('FAW', '$fecha'),
('FERRARI', '$fecha'),
('FIAT', '$fecha'),
('FORD', '$fecha'),
('FORLAND', '$fecha'),
('FOTON', '$fecha'),
('FREIGHTLINER', '$fecha'),
('GEELY', '$fecha'),
('GEO', '$fecha'),
('GMC', '$fecha'),
('GONOW', '$fecha'),
('GREAT WALL', '$fecha'),
('GURGEL', '$fecha'),
('HAFEI', '$fecha'),
('HAIMA', '$fecha'),
('HILLMAN', '$fecha'),
('HINO', '$fecha'),
('HONDA', '$fecha'),
('HOWO', '$fecha'),
('HUMMER', '$fecha'),
('HYUNDAI', '$fecha'),
('INTERNATIONAL', '$fecha'),
('ISUZU', '$fecha'),
('IVECO', '$fecha'),
('JAC', '$fecha'),
('JAGUAR', '$fecha'),
('JEEP', '$fecha'),
('JINBEI', '$fecha'),
('JMC', '$fecha'),
('KAMAZ', '$fecha'),
('KENWORTH', '$fecha'),
('KIA', '$fecha'),
('KING LONG', '$fecha'),
('LADA', '$fecha'),
('LAND ROVER', '$fecha'),
('LANDWIND', '$fecha'),
('LEXUS', '$fecha'),
('LIFAN', '$fecha'),
('LINCOLN', '$fecha'),
('MACK', '$fecha'),
('MAHINDRA', '$fecha'),
('MASERATI', '$fecha'),
('MAZDA', '$fecha'),
('MERCEDES BENZ', '$fecha'),
('MERCURY', '$fecha'),
('MG', '$fecha'),
('MINI', '$fecha'),
('MINKS', '$fecha'),
('MITSUBISHI', '$fecha'),
('NISSAN', '$fecha'),
('OLDSMOBILE', '$fecha'),
('OPEL', '$fecha'),
('PEUGEOT', '$fecha'),
('PIAGGIO', '$fecha'),
('PLYMOUTH', '$fecha'),
('POLSKY FIAT', '$fecha'),
('PONTIAC', '$fecha'),
('PORSCHE', '$fecha'),
('RENAULT', '$fecha'),
('SAMSUNG', '$fecha'),
('SATURN', '$fecha'),
('SCANIA', '$fecha'),
('SCION', '$fecha'),
('SEAT', '$fecha'),
('SHIFENG', '$fecha'),
('SINOTRUCK', '$fecha'),
('SMART', '$fecha'),
('SSANGYONG', '$fecha'),
('SUBARU', '$fecha'),
('SUZUKI', '$fecha'),
('TAVRIA', '$fecha'),
('TOYOTA', '$fecha'),
('TRAILMOBILE', '$fecha'),
('TRIUMPH', '$fecha'),
('TUBULAR', '$fecha'),
('VOLKSWAGEN', '$fecha'),
('VOLVO', '$fecha'),
('WUYANG', '$fecha'),
('YAMAHA', '$fecha'),
('YUGO', '$fecha'),
('ZOTYE', '$fecha');

		");
		DB::statement("
			INSERT INTO `vehicle_types` (`name`,`created_at`) values
('AUTO', '$fecha'),
('CAMIONETA', '$fecha'),
('PICK UP', '$fecha'),
('OMNIBUS', '$fecha'),
('MICROBUS', '$fecha'),
('CAMION', '$fecha');
		");
		DB::statement("
			INSERT INTO `use_types` (`name`,`created_at`) values
('USO PARTICULAR', '$fecha'),
('USO ALQUILER', '$fecha'),
('SERVICIO URBANO', '$fecha'),
('SERV TUR/ESC/PERS', '$fecha'),
('USO CARGA', '$fecha'),
('INTERPROVINCIAL (RUTA CORTA)', '$fecha');
		");
		DB::statement("
		INSERT INTO `insurance_categories` (`name`, `alias`, `use_type_id`, `created_at`) VALUES
('CMTAS PICK UP NO CHINO/NO INDIO', 'NO CHINO/NO INDIO', 1, '$fecha'),
('CMTAS PICK UP CHINO/INDIO', 'PICK UP CHINO/INDIO', 1, '$fecha'),
('AUTOS - CMTAS PANEL - SW Y CMTAS RURALES - PICK UP (RENT A CAR)', 'CHINAS/INDIAS/T C', 2, '$fecha'),
('AUTOS - CMTAS PANEL - SW Y CMTAS RURALES - PICK UP (CONTRATIS)', 'CONTRATIS', 2, '$fecha'),
('AUTOS - SW Y CMTAS RURALES NO CHINO/NO INDIO', 'NO CHINO/NO INDIO', 3, '$fecha'),
('AUTOS - SW Y CMTAS RURALES CHINO/ INDIO', 'CHINO/ INDIO', 3, '$fecha'),
('AUTOS - SW Y CMTAS RURALES TIMON CAMBIADO', 'TIMON CAMBIADO', 3, '$fecha'),
('OMNIBUS Y MICROBUS (NO CMTA RURAL)', 'OMNIBUS Y MICROBUS', 3, '$fecha'),
('CMTAS RURALES, MICROBUS Y OMNIBUS TRANSP ESCOLAR Y PERSONAL', 'TRANSP ESCOLAR Y PERSONAL', 4, '$fecha'),
('MICROBUS Y OMNIBUS TRANS TURIS (NO RURAL)', 'TRANS TURIS (NO RURAL)', 4, '$fecha'),
('CAMION', 'CAMION', 5, '$fecha'),
('CMTA RURAL /OMNIBUS /MICROBUS', 'CMTA RURAL /OMNIBUS /MICR', 6, '$fecha'),
('AUTOS - CMTAS PANEL - SW Y CMTAS RURALES ALTO RIESGO', 'ALTO RIESGO', 1, '$fecha'),
('AUTOS - CMTAS PANEL - SW Y CMTAS RURALES BAJO RIESGO', 'BAJO RIESGO', 1, '$fecha'),
('AUTOS - CMTAS PANEL - SW Y CMTAS RURALES MEDIANO RIESGO', 'MEDIANO RIESGO', 1, '$fecha'),
('AUTOS - CMTAS PANEL - SW Y CMTAS RURALES CHINAS/INDIAS/T C', 'CHINAS/INDIAS/T', 1, '$fecha');
		");
	}
}